version: "3"

services:
  nginx:
    container_name: ${PROJECT_NAME}_nginx
    image: nginx:latest
    volumes:
      - ./${BACKEND_DIR}:/var/www
      - ./.docker/backend/nginx/:/etc/nginx/conf.d
    ports:
      - ${BACKEND_NGINX_PORT}
    depends_on:
      - php
    working_dir: /var/www

  php:
    container_name: ${PROJECT_NAME}_php
    build:
      context: .
      dockerfile: ./.docker/backend/php/Dockerfile
    ports:
      - "8000:8000"
    user: "1000:1000"
    volumes:
      - ./${BACKEND_DIR}:/var/www
    depends_on:
      - database

  database:
    container_name: ${PROJECT_NAME}_database
    image: postgres:12.9
    restart: always
    volumes:
      - ./${BACKEND_DIR}/tmp/db:/var/lib/postgresql
    ports:
      - ${PG_PORTS}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

